version: "3"
services:
  api:
    container_name: django
    image: django-image:v1
    build: .
    command: ./wait-for-it.sh pgadmin:80 -- python manage.py runserver 0.0.0.0:8000
    ports:
      - 8200:8000
    depends_on:
      - db
    networks:
      - postgres
      
  db:
    container_name: db
    image: postgres:latest
    restart: always
    user: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
    ports:
      - 5400:5432
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    volumes: 
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 5050:80
    networks:
      - postgres
          
volumes:
  pgdata:
  pgadmin:

networks:
  postgres:
